---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base
patches:
  - path: mysql-image-patch-for-4.7.yaml
    target:
      group: apps.openshift.io
      version: v1
      kind: DeploymentConfig
      name: catalogue-db
  - path: ./gp2.yaml
    target:
      version: v1
      kind: PersistentVolumeClaim

